### ISSUE TITLE
Currencies and cartJS compatibility? 

### ISSUE THREAD

**Issue by modestasu** [carolineschnapp/currencies#11]
Hey

I'm working on a site at the moment that need to switch between multiple currencies and have ajax cart. I'm using https://cartjs.org/ for cart stuff and just noticed a problem after adding your plugin. Before calling 'convertAll' cart shows money correctly, after it shows zeros with correct currency symbol. Everywhere else on the site money is shown correctly. Once I click 'Checkout', money is shown correctly as well. 

Has anyone tried to integrate these two? Is this a known issue? There's no Javascript errors in console.

Thanks!

**Comment by modestasu** [comment]
Found solution. I was missing "currency": "{{ shop.currency }}" when initiating cartJS on my site.

$(function() {
   CartJS.init({{ cart | json }}, {
      'currency': '{{ shop.currency }}',
      'moneyFormat': '{{ shop.money_format }}',
      'moneyWithCurrencyFormat': '{{ shop.money_with_currency_format }}'
   });
});

**Comment by vemundeldegard** [comment]
I am wondering how called 'convertAll' in your code? I am stuck at the same issue...
