### ISSUE TITLE
data-currency not being written to Product page? (working fine on Shop overview)

### ISSUE THREAD

**Issue by j-greig** [carolineschnapp/currencies#4]
I've added a switcher between GBP and RUB which works fine on the Shop overview page:

`<span class="money" data-currency-gbp="£90.00" data-currency-rub="&amp;#1088;&amp;#1091;&amp;#1073;6.944,38 RUB" data-currency="GBP">£90.00</span>`

But on the single product page, no currency data is being written to the span... any ideas why?

`<span class="product-price-minimum money" data-currency-gbp="">£90.00</span>`

Thanks :)

**Comment by carolineschnapp** [comment]
@j-greig Keep your selectCallback function available to the global scope (window.selectCallback) so that the multiple currencies code is able to override it.
